# Generated by Django 4.0 on 2021-12-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
    ]
