# Generated by Django 4.0 on 2021-12-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_remove_usertariff_tariff_usertariff_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertariff',
            options={'verbose_name': 'Тариф пользователя', 'verbose_name_plural': 'Тарифы пользователя'},
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tariff'),
        ),
        migrations.CreateModel(
            name='TariffHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_at', models.DateTimeField(auto_now_add=True)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tariff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'История тарифов',
                'verbose_name_plural': 'История тарифов',
            },
        ),
    ]
