# Generated by Django 4.0 on 2021-12-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0008_alter_tariffhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertariff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
