# Generated by Django 4.0 on 2021-12-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_alter_usertariff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffhistory',
            name='desc',
            field=models.TextField(blank=True, max_length=255, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='tariffhistory',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Отклонено'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='desc',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariffhistory',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='tariffhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('desc', models.TextField(max_length=255, verbose_name='Сообщение')),
                ('answer', models.TextField(max_length=255, verbose_name='Ответ')),
                ('status', models.BooleanField(verbose_name='Ответ дан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('engineer', models.ForeignKey(limit_choices_to={'groups__name': 'engineer'}, on_delete=django.db.models.deletion.CASCADE, related_name='Инженер', to='auth.user', verbose_name='Инженер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
    ]
