# Generated by Django 4.0 on 2021-12-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0012_alter_usertariff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Инженер'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Инженер', to='auth.user', verbose_name='Инженер'),
        ),
    ]
