# Generated by Django 4.0 on 2021-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_complaint_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertariff',
            name='is_paid',
            field=models.DateField(null=True, verbose_name='Оплачено до'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='answer',
            field=models.TextField(blank=True, max_length=255, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Ответ дан'),
        ),
    ]
