# Generated by Django 4.0 on 2021-12-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usertariff_is_paid_alter_complaint_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertariff',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
