# Generated by Django 4.0 on 2021-12-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0018_tariffhistory_engineer_alter_usertariff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertariff',
            name='engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Инженер'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to='auth.user', verbose_name='Инженер'),
        ),
    ]
