# Generated by Django 4.0 on 2021-12-25 20:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0019_usertariff_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffhistory',
            name='engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Инженер'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Обработал', to='auth.user', verbose_name='Отклонил'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Инженер'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Engineer', to='auth.user', verbose_name='Активировал'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('desc', models.TextField(max_length=255, verbose_name='Сообщение')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79992345679'", regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}$')], verbose_name='Номер телефона')),
                ('status', models.BooleanField(default=False, verbose_name='Ответ дан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
